import type { AudioSource } from 'expo-audio';

/**
 * Narration recorded ahead of time, by clip key.
 *
 * Generated by `node scripts/voice.mjs build`. Empty until that has been run, and the app is
 * built to work that way: with no clip for a block, the device's own voice speaks it.
 *
 * Metro resolves require() at build time, so this map cannot be built at runtime from a
 * directory listing — the script writes the requires out.
 */
export const NARRATION_AUDIO: Record<string, AudioSource> = {};
