import { readFileSync } from 'node:fs';

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { EXERCISES, IMAGE_KEY_BY_MUSCLE_GROUP, muscleGroupOf, photoSlug } from '../src/features/fitness/exercises';

describe('muscleGroupOf', () => {
  it('finds the group of every exercise in the catalogue', () => {
    for (const exercise of EXERCISES) {
      expect(muscleGroupOf(exercise.name), exercise.name).toBe(exercise.group);
    }
  });

  it('ignores case and surrounding spaces, which a stored name can carry', () => {
    const first = EXERCISES[0];
    expect(muscleGroupOf(`  ${first.name.toUpperCase()} `)).toBe(first.group);
  });

  it('returns null for a name it does not know, rather than guessing a group', () => {
    // The real case: a plan generated in French, read by a catalogue rendered in English. A wrong
    // group would silently put the legs photograph on a shoulder press.
    expect(muscleGroupOf('Squat sauté')).toBeNull();
    expect(muscleGroupOf('')).toBeNull();
  });
});

describe('IMAGE_KEY_BY_MUSCLE_GROUP', () => {
  it('covers every group the catalogue actually uses', () => {
    for (const exercise of EXERCISES) {
      expect(IMAGE_KEY_BY_MUSCLE_GROUP[exercise.group], exercise.group).toBeDefined();
    }
  });
});

describe('photoSlug', () => {
  it('gives every exercise a distinct file name', () => {
    const slugs = EXERCISES.map((exercise) => photoSlug(exercise.name));
    expect(slugs.filter((slug) => slug === null)).toEqual([]);
    expect(new Set(slugs).size).toBe(EXERCISES.length);
  });

  it('is null for a name the catalogue does not know', () => {
    // A renamed exercise loses its photograph rather than keeping the old movement's.
    expect(photoSlug('Squat sauté à une jambe')).toBeNull();
  });

  it('only uses characters that are safe in a file name', () => {
    for (const exercise of EXERCISES) {
      expect(photoSlug(exercise.name), exercise.name).toMatch(/^[a-z0-9]+(-[a-z0-9]+)*$/);
    }
  });
});

describe('the photograph lookup, in French', () => {
  // The bug this locks down: `name` goes through t(), so on a French phone it reads “Squat au
  // poids du corps”. A slug derived from it looked for squat-au-poids-du-corps, found nothing,
  // and every one of the 56 exercises fell back to its muscle group — invisibly, because the
  // group image for legs is also somebody squatting. The tests ran in English and saw none of it.
  beforeEach(() => {
    vi.resetModules();
    vi.doMock('expo-localization', () => ({ getLocales: () => [{ languageCode: 'fr' }] }));
  });
  afterEach(() => vi.doUnmock('expo-localization'));

  it('finds the same photograph whichever language the name was stored in', async () => {
    const fr = await import('../src/features/fitness/exercises');
    for (const exercise of fr.EXERCISES) {
      // The name here is already the French one, since the module was loaded in French.
      expect(fr.photoSlug(exercise.name), exercise.slug).toBe(exercise.slug);
    }
  });

  it('still answers to the English name a plan generated before the phone changed language', async () => {
    const fr = await import('../src/features/fitness/exercises');
    expect(fr.photoSlug('Bodyweight squat')).toBe('bodyweight-squat');
    expect(fr.photoSlug('Wall sit')).toBe('wall-sit');
  });
});

describe('the photograph manifest', () => {
  it('is keyed by the catalogue slugs and nothing else', () => {
    // Read as text, not imported: the module require()s JPEGs, which only Metro resolves.
    // It is generated by scripts/exercise-photos.mjs from the same field, so a rename that
    // touches one side and not the other fails here instead of showing the wrong picture.
    const source = readFileSync('src/theme/exercisePhotos.ts', 'utf8');
    const keys = [...source.matchAll(/^ {2}'([a-z0-9-]+)':/gm)].map((match) => match[1]);
    const catalogue = new Set(EXERCISES.map((exercise) => exercise.slug));
    expect(keys.length).toBeGreaterThan(0);
    expect(keys.filter((slug) => !catalogue.has(slug))).toEqual([]);
    // Both directions, and this is the one that matters: a photograph missing from the manifest
    // does not break anything, it quietly shows the muscle group instead — which is how fifty-six
    // wrong pictures went unnoticed for a week. An extra key fails loudly at bundling time; a
    // missing one fails nowhere, so it has to fail here.
    const keyed = new Set(keys);
    expect(EXERCISES.filter((exercise) => !keyed.has(exercise.slug)).map((e) => e.slug)).toEqual([]);
  });
});
