import type { ImageSourcePropType } from 'react-native';

// Generated by scripts/exercise-photos.mjs — do not edit by hand.
// Keyed by photoSlug() from src/features/fitness/exercises.ts.
export const EXERCISE_PHOTOS: Record<string, ImageSourcePropType> = {
  'alternating-lunges': require('../../assets/images/exercises/alternating-lunges.jpg'),
  'barbell-back-squat': require('../../assets/images/exercises/barbell-back-squat.jpg'),
  'bodyweight-squat': require('../../assets/images/exercises/bodyweight-squat.jpg'),
  'bulgarian-split-squat-with-dumbbells': require('../../assets/images/exercises/bulgarian-split-squat-with-dumbbells.jpg'),
  'goblet-squat': require('../../assets/images/exercises/goblet-squat.jpg'),
  'jump-squat': require('../../assets/images/exercises/jump-squat.jpg'),
  'wall-sit': require('../../assets/images/exercises/wall-sit.jpg'),
};
